import { Link } from 'react-router-dom'; import { ArrowRight, CheckCircle } from 'lucide-react';
const data:any={
namibia:['Namibia','The first core Padmaats destination','A gateway to Namibia travel inspiration, practical planning and trusted travel pathways.','namibia-dunes.jpg',['Destination inspiration','Self-drive routes','Places to stay','Car hire / 4x4','Travel guides']],
selfdrive:['Namibia Self-Drive','Freedom to explore','Road-trip and self-drive inspiration with practical information for planning a memorable Namibia journey.','self-drive.jpg',['Route inspiration','Road-trip planning','Vehicle considerations','Practical travel tips','Partner pathways']],
stay:['Stay in Namibia','Places worth remembering','Accommodation partner content designed to grow as approved travel-trade relationships develop.','stay-namibia.jpg',['Accommodation inspiration','Trusted partner links','Flexible provider structure','Easy future additions']],
car:['Car Hire / 4x4','Your road starts here','Vehicle-rental partner content for travellers planning self-drive adventures across Namibia.','car-hire.jpg',['Rental partner pathways','4x4 travel inspiration','Trackable outbound links','Replaceable partner structure']],
journeys:['Padmaats Journeys','Travel together, discover deeper','A reusable home for Padmaats’ own hosted and curated journeys, current opportunities and future departures.','journey-roadtrip.jpg',['Hosted journeys','Curated experiences','Register-interest enquiries','Reusable journey template']],
churches:['Seven Churches 2027','A journey of faith and discovery','A dedicated interest page for the existing Türkiye Seven Churches 2027 journey.','journey-roadtrip.jpg',['Journey overview','Register interest','Direct enquiry pathway','Future updates']],
guides:['Travel Guides & Stories','Inspiration for the road ahead','A reusable editorial structure for destination guides, road-trip stories and practical travel content.','namibia-dunes.jpg',['Destination guides','Road-trip stories','Practical advice','Search-friendly articles']],
plan:['Plan & Book','Simple pathways, trusted partners','A practical hub connecting travellers to Stay, Drive, Flights and Experiences through approved links or enquiries.','self-drive.jpg',['Stay','Drive','Flights','Experiences','Enquiry support']],
about:['About Padmaats','Saam op pad','Padmaats is a travel platform built around discovery, practical planning, meaningful journeys and trusted connections.','hero-namibia.jpg',['Warm and practical travel','Curated journeys','Trusted partnerships','Built to grow']],
legal:['Legal & Disclosures','Clear, responsible travel content','A structured home for privacy, terms, affiliate disclosures and related legal information.','hero-namibia.jpg',['Privacy notice','Terms of use','Affiliate disclosure','Marketing consent']]
};
export default function ContentPage({type}:{type:string}){const [title,kicker,desc,img,items]=data[type]||data.namibia;return <><section className="relative h-[430px] flex items-end"><img src={'/images/'+img} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#07344a]/90 via-[#07344a]/25 to-transparent"/><div className="relative max-w-7xl mx-auto px-5 pb-14 w-full text-white"><p className="uppercase tracking-[.25em] text-[#f4c154] text-sm font-bold">{kicker}</p><h1 className="text-5xl md:text-6xl font-serif font-bold mt-2">{title}</h1></div></section><section className="py-20 bg-[#fffaf2]"><div className="max-w-5xl mx-auto px-5 grid md:grid-cols-[1.5fr_1fr] gap-12"><div><h2 className="pad-heading">Explore with Padmaats</h2><p className="text-lg leading-8 text-slate-600">{desc}</p><p className="mt-5 text-slate-600 leading-7">This Phase 1 structure is intentionally lean and reusable so future destinations, journeys, travel guides and approved partners can be added without rebuilding the platform from scratch.</p><Link to="/contact" className="pad-btn mt-8">Enquire / Register Interest <ArrowRight size={17}/></Link></div><div className="bg-white rounded-2xl p-7 shadow-sm"><h3 className="font-serif text-2xl font-bold text-[#07344a] mb-5">On this pathway</h3>{items.map((x:string)=><div className="flex gap-3 py-3 border-b last:border-0" key={x}><CheckCircle size={19} className="text-[#496b35] shrink-0"/><span>{x}</span></div>)}</div></div></section></>}
