import { Link } from 'react-router-dom';
import { Compass, Car, BedDouble, Users, ArrowRight, Map, Heart, BookOpen } from 'lucide-react';
const A='/images/';
const cards=[['Namibia','Vast landscapes, wildlife and unforgettable horizons.','namibia-dunes.jpg','/namibia'],['Self-Drive Namibia','Practical road-trip inspiration and freedom to explore.','self-drive.jpg','/namibia/self-drive'],['Stay in Namibia','Discover accommodation partners and memorable places to stay.','stay-namibia.jpg','/stay-in-namibia'],['Car Hire / 4x4','Find trusted vehicle-rental pathways for your journey.','car-hire.jpg','/car-hire-4x4']];
export default function Home(){return <div className="page-enter">
<section className="relative min-h-[620px] flex items-center overflow-hidden bg-[#f7f0e5]"><img src={A+'hero-namibia.jpg'} className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-[#f7f0e5] via-[#f7f0e5]/85 to-transparent"/><div className="relative max-w-7xl mx-auto px-5 py-24 w-full"><div className="max-w-2xl"><p className="tracking-[.3em] uppercase text-sm font-bold text-[#496b35] mb-4">Explore • Experience • Journey</p><h1 className="text-5xl md:text-7xl font-serif font-bold text-[#07344a] leading-[.95]">Discover Namibia<br/><span className="text-[#496b35] italic font-normal">and beyond</span></h1><p className="mt-7 text-lg text-slate-700 max-w-xl">Inspiring travel experiences, self-drive adventures, unique stays and curated journeys — starting with Namibia.</p><div className="flex flex-wrap gap-3 mt-8"><Link to="/namibia" className="pad-btn">Explore Namibia <ArrowRight size={17}/></Link><Link to="/journeys" className="pad-btn-outline">View Journeys <ArrowRight size={17}/></Link></div></div></div></section>
<section className="bg-[#07344a] text-white"><div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-0">{[[Compass,'Curated Journeys'],[Car,'Self-Drive Adventures'],[BedDouble,'Unique Stays'],[Users,'Trusted Partners']].map(([I,t]:any)=><div className="p-6 flex gap-3 items-center border-white/10 border-r" key={t}><I className="text-[#e7a51e]"/><span className="font-semibold">{t}</span></div>)}</div></section>
<section className="py-20 bg-[#fffaf2]"><div className="max-w-7xl mx-auto px-5"><p className="eyebrow">Featured destination</p><h2 className="pad-heading">Start Your Next Adventure</h2><p className="text-slate-600 max-w-3xl mb-10">Phase 1 establishes Namibia as Padmaats’ first core destination while creating reusable pathways for future destinations, journeys, guides and partners.</p><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">{cards.map(([t,d,img,url])=><Link to={url} key={t} className="group bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-xl transition"><img src={A+img} className="w-full h-48 object-cover group-hover:scale-105 transition duration-500"/><div className="p-5"><h3 className="text-xl font-serif font-bold text-[#07344a]">{t}</h3><p className="text-sm text-slate-600 mt-2">{d}</p><span className="inline-flex mt-4 text-[#496b35] font-bold text-sm items-center gap-1">Explore <ArrowRight size={14}/></span></div></Link>)}</div></div></section>
<section className="py-20 bg-white"><div className="max-w-7xl mx-auto px-5 grid lg:grid-cols-2 gap-12 items-center"><img src={A+'journey-roadtrip.jpg'} className="rounded-3xl shadow-xl w-full h-[430px] object-cover"/><div><p className="eyebrow">Travel that connects</p><h2 className="pad-heading">Saam op pad.</h2><p className="text-slate-600 leading-7">Padmaats is being built as a warm, practical and expandable travel platform: destination inspiration, hosted journeys, trusted travel partners and simple enquiry pathways — without unnecessary complexity at launch.</p><div className="grid sm:grid-cols-2 gap-4 mt-7">{[[Map,'Plan & Book','Stay, drive, flights and experiences'],[BookOpen,'Travel Guides','Stories, road trips and practical advice'],[Heart,'Padmaats Journeys','Hosted and curated opportunities'],[Compass,'Seven Churches 2027','Register interest in the Türkiye journey']].map(([I,t,d]:any)=><div className="p-4 rounded-xl bg-[#f7f0e5]"><I className="text-[#e7a51e] mb-2"/><b className="block text-[#07344a]">{t}</b><span className="text-sm text-slate-600">{d}</span></div>)}</div><Link to="/plan-book" className="pad-btn mt-7">Plan Your Journey <ArrowRight size={17}/></Link></div></div></section>
<section className="py-16 bg-[#496b35] text-white text-center"><div className="max-w-3xl mx-auto px-5"><h2 className="text-3xl md:text-5xl font-serif font-bold">Ready to start planning?</h2><p className="mt-4 text-white/80">Tell Padmaats what kind of journey you have in mind and start the conversation.</p><Link to="/contact" className="inline-flex mt-7 bg-[#e7a51e] text-[#07344a] px-6 py-3 rounded-full font-bold">Send an enquiry</Link></div></section>
</div>}
